### ISSUE TITLE
 cannot download features for each dataset

### ISSUE THREAD

**Issue by SiyuLou** [oncescuandreea/audio-retrieval#1]
Hi, 
I tried to download features for each dataset, following the link https://github.com/oncescuandreea/audio-experts/blob/audiocaps/misc/exps-names.md. however can't access the page, it shows Page not found. could you please help ?

Thank you!

**Comment by oncescuandreea** [comment]
Hi,

Thanks for flagging this issue. I think it should work now. Please let me know if not.
